// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJuVKMkHycrSc9NY3Qfy91oknT59Wmhzw',
    appId: '1:908008172444:web:153cfc55a772fed745b659',
    messagingSenderId: '908008172444',
    projectId: 'ffhera',
    authDomain: 'ffhera.firebaseapp.com',
    databaseURL: 'https://ffhera-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ffhera.appspot.com',
    measurementId: 'G-C5200QLM0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYpXl914rrP9Dyn-Z70eqgNx6FiQPjWWE',
    appId: '1:908008172444:android:3c220fe5483a1f0e45b659',
    messagingSenderId: '908008172444',
    projectId: 'ffhera',
    databaseURL: 'https://ffhera-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ffhera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz4T76tkNNesUa80KpP7t3vUHBryR3iIE',
    appId: '1:908008172444:ios:3527dad8e958873e45b659',
    messagingSenderId: '908008172444',
    projectId: 'ffhera',
    databaseURL: 'https://ffhera-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ffhera.appspot.com',
    iosBundleId: 'com.example.healthEmergencyResponseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz4T76tkNNesUa80KpP7t3vUHBryR3iIE',
    appId: '1:908008172444:ios:623c958bf6ab1ed845b659',
    messagingSenderId: '908008172444',
    projectId: 'ffhera',
    databaseURL: 'https://ffhera-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ffhera.appspot.com',
    iosBundleId: 'com.example.healthEmergencyResponseApp.RunnerTests',
  );
}
